### ISSUE TITLE
Got ERROR while deleting a pvc

### ISSUE THREAD

**Issue by leo1971** [AliyunContainerService/csi-plugin#2]
This is my `storageclass.yaml`:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-disk
provisioner: csi-diskplugin
parameters:
    zoneId: cn-shanghai-b
    regionId: cn-shanghai
    fsType: ext4
    type: cloud_ssd
    readOnly: "false"
reclaimPolicy: Delete
```

I set `reclaimPolicy` to `Delete`, that means a volume will be automatically deleted when I delete the corresponding pvc, but after I delete a pvc, I got this message:
```
 rpc error: code = Unknown desc = Delete disk 3 times, but error: Aliyun API Error: RequestId: 526A2F7D-BF04-4F9C-8BED-DCA19603EDDC Status Code: 403 Code: IncorrectDiskStatus Message: The current disk status does not support this operation.
```

Any help would be greatly appreciated.
