### ISSUE TITLE
deploy/oss中没有oss-attacher.yaml，是文档没有更新吗？

### ISSUE THREAD

**Issue by hfrzhanghao** [AliyunContainerService/csi-plugin#59]
deploy/oss中没有oss-attacher.yaml，是文档没有更新吗？

**Comment by fredkan** [comment]
oss不需要attacher，直接mount就可以了。

**Comment by fredkan** [comment]
```
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: ossplugin.csi.alibabacloud.com
spec:
  attachRequired: false
```

上面配置，可以让csi不去调用attach接口，所以不需要部署attacher。
