### ISSUE TITLE
请问ESSD云盘如何指定性能级别？

### ISSUE THREAD

**Issue by wclw** [AliyunContainerService/csi-plugin#63]
![image](https://user-images.githubusercontent.com/50645123/62844421-e1a0d700-bcf3-11e9-91f9-e5cc7fdbc934.png)
ESSD云盘有3个性能级别，不知在YAML文件中如何指定？

**Comment by fredkan** [comment]
latest csiplugin support it:
https://github.com/AliyunContainerService/csi-plugin/tree/master/deploy/ack

add performanceLevel in storageclass:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: alicloud-disk-essd-pl2
provisioner: diskplugin.csi.alibabacloud.com
parameters:
  type: cloud_essd
  performanceLevel: PL2
  zoneId: cn-hangzhou-i
reclaimPolicy: Delete
```
