### ISSUE TITLE
Delete a pod, the old volume is not attached to the pod correctly

### ISSUE THREAD

**Issue by jia-jerry** [AliyunContainerService/csi-plugin#8]
1. k8s, single worker node, version 1.11.0
2. cis, version v0.3.0
3. apply example Yaml below.
4. get into nginx pod, and create a file in /data by ```touch test```
5. delete current nginx pod
6. get into the new nginx pod, the /data folder is wrongly mounted.
---
Root cause: the disk is attached from the machine.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: csi-disk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment1
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
          - name: disk-pvc
            mountPath: "/data"
      volumes:
        - name: disk-pvc
          persistentVolumeClaim:
            claimName: disk-pvc
```
